### ISSUE TITLE
학교 코드가 안불러와지는곳이 있는 것 같아요

### ISSUE THREAD

**Issue by jugol** [5d-jh/school-menu-api#1]
부산대학교사범대학부설고등학교

를 불러오려고 하는데 지역 코드가 잘못되었다고 하네요 ㅠㅠ 맨 앞글자를 다시 확인하라구..

나머지 고등학교들은 잘 되더라구요근데

**Comment by 5d-jh** [comment]
국립고등학교를 생각 못했네요..ㅠㅠ 빠른 시일 내에 수정하도록 하겠습니다
