### ISSUE TITLE
급식이 중간에 표시되지 않습니다.

### ISSUE THREAD

**Issue by junh1127** [5d-jh/school-menu-api#10]
https://schoolmenukr.ml/api/high/Q100000188

확인바랍니다.감사합니다.

**Comment by 5d-jh** [comment]
해당 문제를 해결하였습니다. 잘 표시되는지 확인 바랍니다.

또한, 현재로부터 다음 달의 식단을 불러오는 경우 3일, 그렇지 않은 경우 3년간 저장한다는 점을 알아두시기 바랍니다. 감사합니다.

**Comment by junh1127** [comment]
문제가 해결되었습니다 감사합니다!

혹시 '현재로부터 다음 달의 식단을 불러오는 경우 3일, 그렇지 않은 경우 3년간 저장한다는 점을 알아두시기 바랍니다'가 세부적으로 어떤 의미인지 여쭈어봐도 될까요?

**Comment by 5d-jh** [comment]
식단을 불러오는 속도를 향상시키기 위해 아마존 서버에 임시 저장하고 있습니다.

현재 버그가 있는 것으로 보여 정확히 말씀드리긴 어렵지만, 예를 들어 2019년 3월에 4월 식단을 불러올 때보다, 2019년 4월에 4월 식단을 불러올 때가 임시 저장 기간이 훨씬 깁니다.

임시 저장 기간이 지난 후 같은 식단을 요청하면 NEIS 서버에서 새로 받아서 보여줍니다.
