### ISSUE TITLE
급식이 뜨지 않는 문제가 재발생하였습니다.

### ISSUE THREAD

**Issue by junh1127** [5d-jh/school-menu-api#11]
이전과 같은 오류입니다. 5월 급식이 표시되지 않습니다.
수고스러우시더라도 다시 한번만 봐주시면 감사하겠습니다.
아울러, 이런 문제가 재발하지 않으려면 어떻게 해야 하는지 알려주시면 감사하겠습니다.

https://schoolmenukr.ml/api/high/Q100000188?month=5

**Comment by 5d-jh** [comment]
5월 급식이 표시되지 않는 문제는 현재 해결된 상태입니다. 혹시 5월달 식단을 언제 처음으로 불러왔는지 기억하고 계신가요?

**Comment by junh1127** [comment]
아니요, 현재 챗봇을 이용해 api를 호출하는 방식이라 제가 체크할수 없는 상태입니다. 혹시 현재 달이 아닌 다음 달을 호출하는 것이 영향이 있다면, 봇 구조적으로 다음 달 조회를 막고 현재 달 조회만 하는 방식으로 바꾼다면 문제가 해결될까요?

**Comment by 5d-jh** [comment]
일단은 그렇게 하면 임시적으로나마 해결할 수 있을 것 같습니다. 제가 지금 바빠서 버그 수정에는 시간이 걸릴 것 같습니다. 만약 Pull Request 해주신다면 검토 후 승인해 드리도록 하겠습니다. 불편을 드려 죄송합니다.

**Comment by 5d-jh** [comment]
테스트 서버에서 저장 기간과 관련하여 수정된 사항이 있습니다. 간단히 테스트한 후 잘 되는지 확인 부탁드립니다.
이 서버에서는 현재보다 앞 월의 식단을 요청하면 저장하지 않고, 지난월의 식단을 요청하면 영구적으로 저장합니다.
https://67t15o8010.execute-api.ap-northeast-2.amazonaws.com/dev/api/

**Comment by junh1127** [comment]
확인하였으나, 예전에 쿼리 변수로 주소 끝에 ?date=9로 9일자 식단만을 불러오던 것이 현재는 작동하지 않는 것 같습니다.

**Comment by junh1127** [comment]
또한 외부에서 api를 불러올때 http 403 에러도 발생하는 것 같습니다.

**Comment by 5d-jh** [comment]
date변수 설정 시 문제가 생기는 오류는 수정했습니다.

두 번째의 경우 403 오류가 어떻게 해서 발생되었는지 구체적으로 알려주시면 감사하겠습니다.

**Comment by junh1127** [comment]
직접 주소에 접속하여 호출할 때는 되는데, 외부 챗봇이나 플랫폼이 호출할 때 권한을 얻지 못하는 것 같습니다. 

상위 주소에 접속하였을때, 기존 페이지는 

{"message":"Missing Authentication Token"}라고 나오지만, 

현재 위에서 제공해주신 페이지에서는 

{"message":"Forbidden"}이라고 나옵니다. 

뭔가 기존과 다른 점이 있어 외부 봇이 호출할 때 권한을 얻지 못하는 것이 아닌가 싶습니다. 

아래는 챗봇이 서버 request 후 받은 메시지입니다.

"Server returned HTTP response code: 403 for URL: https://67t15o8010.execute-api.ap-northeast-2.amazonaws.com/dev/api/high/Q100000188"

**Comment by 5d-jh** [comment]
```js
const request = require('request');

const url = 'https://67t15o8010.execute-api.ap-northeast-2.amazonaws.com/dev/api/high/Q100000188';
request(url, (err, res, body) => {
    var json = JSON.parse(body);
    console.log(json);
});
```
일반 주소로 접속해서 정상적으로 불러와진다면 프로그램 내에서 호출할 때도 정상적으로 불러와지는 게 일반적입니다. 또한 제가 이 코드로 테스트해본 결과 별 이상 없이 잘 불러와집니다.

중간에 AWS 권환과 관련하여 변경 사항이 있었습니다. 그것과 관련하여 오류를 일으킨 것일지도 모릅니다. 수고스러우실지라도 한 번 다시 테스트해 보시기 바랍니다. 불편을 드려 죄송합니다.

**Comment by 5d-jh** [comment]
https://6zrq6ri2ah.execute-api.ap-northeast-2.amazonaws.com/dev/api/

테스트 서버 URL이 변경되었습니다. 간단한 테스트 부탁드립니다.
