### ISSUE TITLE
[버그] 메뉴를 불러올 수 없음

### ISSUE THREAD

**Issue by Sene1** [5d-jh/school-menu-api#116]
**버그에 대해 설명해 주세요.**
어떤 버그인지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴가 뜨지 않습니다.)
급식 메뉴를 불러올 수 없음

**요청 URL**
어떤 URL로 요청해야 버그를 볼 수 있는지 알려주세요. (예: schoolmenukr.ml/api/high/ASDF?year=2020)

https://schoolmenukr.ml/api/high/N100000191?year=2022&month=3&date=16

**원래 예상했던 결과**
원래 어떤 결과가 나와야 하는지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴도 떠야 합니다.)

친환경찹쌀밥
오징어김치전
1.5.6.9.13.17.
볼어묵채소 볶음
1.5.6.13.16.
영양부추무침
13.
석박지
9.
모듬순대국밥
2.5.6.10.13.16.

**추가 정보**
버그와 관련된 추가 정보가 있다면 적어주세요.

**Comment by 5d-jh** [comment]
식단 정보를 업데이트했습니다. 다시 확인 부탁드립니다.

**Comment by Sene1** [comment]
이제 잘 불러와지네요!
