### ISSUE TITLE
hideAllergy=true를 해도 *이 남아있습니다.

### ISSUE THREAD

**Issue by khhandrea** [5d-jh/school-menu-api#12]
직접 지울 순 있지만.. 기본적으로 *도 추가적으로 컨트롤할 수 있으면 합니다

**Comment by 5d-jh** [comment]
테스트 서버에 * 도 컨트롤할 수 있도록 수정해 놓았습니다. 간단히 테스트해 보시고 문제가 없는지 확인 바랍니다.

https://67t15o8010.execute-api.ap-northeast-2.amazonaws.com/dev/api/

**Comment by khhandrea** [comment]
메일을 못봤네요ㅠㅠ
신경 써주셔서 감사한데 서버 닫은건가요? 아직 확인을 못한건가요..
 
-----Original Message-----

**Comment by 5d-jh** [comment]
테스트 서버 URL을 변경하였습니다.

https://anuwkxfv6b.execute-api.ap-northeast-2.amazonaws.com/dev/api/

**Comment by khhandrea** [comment]
예전 url 변경되었다는 url 모두 
message : "Internal Server Error"가 뜹니다..
아래 보내주신 변경된 테스트 서버 링크가 뭘 의미하는건가요? 어떻게 사용하는건가요
 
-----Original Message-----

**Comment by 5d-jh** [comment]
브랜치간 이동으로 인해 모듈 문제가 있었던 것 같습니다. 현재는 수정된 상태입니다

https://6zrq6ri2ah.execute-api.ap-northeast-2.amazonaws.com/dev/api/

**Comment by khhandrea** [comment]
감사합니다 잘 되네요
정식 url로 바꿔주시는건가요?
-----Original Message-----

**Comment by 5d-jh** [comment]
넵 곧 그럴 예정입니다. 개발 환경 운영에 미숙한 점 사과 드립니다.
