### ISSUE TITLE
매개변수 date 오류

### ISSUE THREAD

**Issue by SonYoonSeok** [5d-jh/school-menu-api#126]
## 설명
매개변수 date가 작동되지 않습니다.

## 재현 방법
`https://schoolmenukr.ml/api/high/G100000170?year=2022&month=3&date=30` 와 같이 요청을 보내면 

## 원래 예상한 결과
2022년 3월 30일에 해당하는 식단만 와야되는데 3월 1일부터 31일까지 전체가 오고 있습니다.

**Comment by 5d-jh** [comment]
수정사항 적용했습니다. 확인 부탁드립니다.

**Comment by SonYoonSeok** [comment]
확인했습니다. 감사합니다
