### ISSUE TITLE
500 오류가 뜹니다

### ISSUE THREAD

**Issue by jhson0531** [5d-jh/school-menu-api#13]
서버리스 애플리케이션에서 두 달 전까지 작동하던 식단표가 500오류를 띄우면서 작동을 하지 않습니다
https://schoolmenukr.ml/api/high/J100000868?date=${_day}&hideAllergy=true 
확인 부탁드려도 될까요...? (_day변수는 문제 없는거 같습니다)

**Comment by 5d-jh** [comment]
안녕하세요. 해당 문제는 저의 AWS 액세스 키 관리 실수 인해 발생한 문제이며, 현재 해결된 상태입니다. 불편을 드려 죄송합니다.

**Comment by jhson0531** [comment]
빠르게 해결해주셔서 감사합니다 좋은 api 무료로 제공해주시는 것도 감사합니다
