### ISSUE TITLE
안녕하세요 배포해주신 API잘사용하다가 최근에 안되는사실을 알았습니다. 확인해주실수있을까요

### ISSUE THREAD

**Issue by qhrms971** [5d-jh/school-menu-api#19]
감사합니다.

**Comment by 5d-jh** [comment]
NEIS 코드 api를 말하시는 건가요? 한번 알아보겠습니다.

**Comment by qhrms971** [comment]
제가 개발자가 아니라서 ㅠㅠ NEIS코드 API인지는 잘모르겠어요 ..
 
=IMPORTjson("https://schoolmenukr.ml/code/api?q="&B1) 
 
제가 구글스프레드시트에서
형태로해서 학교코드 찾는걸 사용했었습니다.

이렇게하면



 
여기에 원래
 
학교코드와 학교명 주소? 같은게 떴었는데
지금은 해당 URL에 서 검색이안됩니다 ㅠ



이런거 만들어주셔서 감사합니다.


-----Original Message-----

**Comment by 5d-jh** [comment]
수정이 늦어서 죄송합니다ㅠㅠ 지금쯤이면 아마 사용하실 수 있을겁니다. 확인 바랄게요

**Comment by qhrms971** [comment]
매우감사드립니다
 
쓰는사람입장으로썬 그냥 해주신것만해도 감사하죠!!
 
지난번하고 조금 달라진거같긴한데! 잘됩니다 감사합니다
 
 
같은 청룡초를 쳤는데
 
서울쪽은 서울청룡하니까 뜨네요 
 
-----Original Message-----

**Comment by 5d-jh** [comment]
네 기술상의 문제로 검색어를 찾는 방식을 바꾸어서 어쩔 수 없는 부분인 것 같습니다ㅠㅠ
