### ISSUE TITLE
Node.js 환경에서 오류

### ISSUE THREAD

**Issue by godrb** [5d-jh/school-menu-api#2]
http://wingnim.tistory.com/8?category=767913
이 게시글을 보고 따라해서 잘 사용하고 있었습니다.
근데 추석 지나고 부터 저희 학교 급식 정보를 불러오지 못합니다.
그냥 급식이 없다고 뜨구요. 김급식에는 잘 뜹니다.
혹시나 해서 근처에 있는 아무 학교나 넣어서 수정 해봤더니 잘 됩니다.
저희 학교 코드는 N100000194 이구요.
문제점 찾아서 해결 해주시면 감사하겠습니다.

**Comment by 5d-jh** [comment]
저의 경우 잘 불러와집니다. 몇월달 급식을 불러오신 건가요?

**Comment by godrb** [comment]
9월달 급식을 불러왔습니다.
혹시나해서 10월달 급식을 불러봤더니 그것도 안 되더군요.

**Comment by 5d-jh** [comment]
https://schoolmenukr.ml/api/high/N100000194?month=9
https://schoolmenukr.ml/api/high/N100000194?month=10

흠.. 위 링크로 요청을 보냈는데 안 되는건가요?
만약 계속 안된다면 주소 맨 끝에 &nodb=true를 붙여서 해 보세요.

**Comment by godrb** [comment]
어이고 ㄷㄷ
그럼 업데이트 될 때까지 급식 플친은 작동을 중지 시켜놔야겠군요.
답변 감사합니다 :)

**Comment by godrb** [comment]
오늘 급식 플친 활성화 해봤는데 정상적으로 급식이 불러와지더군요.
왜 해결 된건지 저도 잘 모르겠는데 암튼 해결 됐으니 다행이네요 ㅋㅋㅋ

**Comment by 5d-jh** [comment]
이번에 DB에 임시 저장 되어 있는 식단을 전부 다 지웠는데 그러면서 최신으로 업데이트됐나보네요. 그게 아니더라도  끝에 nodb를 붙였다면 되어야했을텐데..🤔

이렇게 도중에 내용이 바뀌는 일이 있어서 임시저장하는 방법으로 데이터베이스 대신 다른 방법을 고안중입니다.
