### ISSUE TITLE
API가 응답하지 않음

### ISSUE THREAD

**Issue by BackGwa** [5d-jh/school-menu-api#212]
## 설명

현재 급식 정보 API가 작동하지 않습니다.
다양한 방법으로 API에게 요청하더라도 어떠한 값도 받지 못하고 있습니다.

> [학교 코드 찾기](https://schoolmenukr.ml/code/app) 또한, 작동하지 않는 것 같습니다.

**현재 이 문제는 API 도메인과 관련된 문제로 생각하고 있습니다.**

## 재현 방법

Python 구현
```python
API = 'https://schoolmenukr.ml/api/high/N100000164'
response = requests.get(API)
```
```
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다
```

## 원래 예상한 결과

급식 정보에 대한 JSON 데이터가 출력되어야합니다.

**Comment by 5d-jh** [comment]
불편을 드려 죄송합니다. DNS 제공사 문제로 주소가 바뀌었습니다. school-api.xyz로 접속 부탁드려요
