### ISSUE TITLE
학교 급식 정보가 불러와지지 않음

### ISSUE THREAD

**Issue by BackGwa** [5d-jh/school-menu-api#214]
## 설명

급식 정보를 정상적으로 반환하지 않습니다.

## 재현 방법

https://school-api.xyz/api/high/N100000164?year=2023&month=4&date=18&allergy=hidden

## 원래 예상한 결과

급식 정보가 원래 정상적으로 반환되어야 합니다.

하지만, 급식 정보 결과를 정상적으로 반환하지 못합니다.
<img width="746" alt="스크린샷 2023-04-18 오후 10 17 47" src="https://user-images.githubusercontent.com/64456214/232789579-58392427-eff2-4d9c-b141-c0a09f76271f.png">

**Comment by 5d-jh** [comment]
데이터베이스를 업데이트해서 조치했습니다. 새로고침 로직을 개선해볼게요
