### ISSUE TITLE
API가 동작하지 않는 문제

### ISSUE THREAD

**Issue by Bluebear645** [5d-jh/school-menu-api#215]
## 설명

API 요청을 보냈을 때 menu가 출력되지 않습니다.

**Comment by 5d-jh** [comment]
차세대 나이스 시스템이 도입됨에 따라 스크래핑을 통해 API 제공이 어려워진걸로 보입니다. 번거로우시겠지만 나이스 교육정보 개방포털에서 제공하는 급식식단정보 API를 활용하시기 바랍니다.

https://open.neis.go.kr/portal/data/service/selectServicePage.do?page=1&rows=10&sortColumn=&sortDirection=&infId=OPEN17320190722180924242823&infSeq=1
