### ISSUE TITLE
stu.xxx.go.kr 에서의 식단표와 출력값이 다름

### ISSUE THREAD

**Issue by gloure** [5d-jh/school-menu-api#3]
![screenshot_2018-10-05-17-07-42-911](https://user-images.githubusercontent.com/43875772/46523762-b5415080-c8c1-11e8-8a81-820b966cb31a.jpeg)

해당사진은 10월 5일 식단표 입니다.
석식 부분에서 받아오는 식단 내용이 다릅니다 확인 부탁드립니다

**Comment by gloure** [comment]
추가로 hideAllergy 속성을 켰는데도 알러지 값을 불러오는 것과, nodb옵션을 적용하면 date 옵션이 적용되지 았습니다

**Comment by 5d-jh** [comment]
hideAllergy는 서버에 올라가 있는 코드가 최신이 아니라서 발생한 문제이며 현재 수정된 상태입니다.

식단 내용이 다른 문제, nodb옵션 적용 시 date 옵션이 미적용되는 문제는 수정하도록 하겠습니다. 식단 내용이 다른 문제는 해결하는 데 시간이 좀 걸릴지도 모르겠습니다..

**Comment by 5d-jh** [comment]
문제가 되는 부분의 코드를 수정하였습니다. 잘 불러와지나요?

**Comment by gloure** [comment]
태풍이 오는데 수고많으시네요
10월 5일 식단표 기준으로 아직 식단은 잘못불러와지네요 ㅠㅠ
nodb와 date옵션은 동시에 적용되는 것 확인 했습니다

**Comment by gloure** [comment]
![screenshot_2018-10-06-20-02-18-491](https://user-images.githubusercontent.com/43875772/46570684-17be4d80-c9a3-11e8-9c45-1b7b68650942.jpeg)
10월 5일 식단

![screenshot_2018-10-06-20-03-52-204](https://user-images.githubusercontent.com/43875772/46570686-260c6980-c9a3-11e8-8ffd-fd5b71ae8e50.jpeg)
10월 15일 식단

석식 제일 마지막 메뉴가 생략되어 버립니다...

**Comment by 5d-jh** [comment]
제가 주의깊게 보지 못했네요..

관련 코드를 수정했습니다. 이제 잘 불어와지나요?

**Comment by gloure** [comment]
해결됐네요 ^^7 수고 많으셨습니다
