### ISSUE TITLE
[버그] 학교 E100002238의 특정 급식 빈칸

### ISSUE THREAD

**Issue by sboh1214** [5d-jh/school-menu-api#34]
**버그에 대해 설명해 주세요.**
학교 E100002238(인천광역시교육청 인천과학예술영재학교)의 특정 급식이 뜨지 않습니다.

**요청 URL**
https://schoolmenukr.ml/api/high/E100002238?year=2020&month=9

**원래 예상했던 결과**
9/18(금) 저녁, 9/19(토) 아침 점심 저녁, 9/20(일) 아침 점심 저녁 급식이 모두 나와야 합니다.

**추가 정보**
neis 학생서비스로 확인해 본 결과 neis 사이트에서는 급식이 정상적으로 표출되고 있습니다.
저희 학교는 기숙학교라서 현재 주7일 아침 점심 저녁이 모두 있습니다.

감사합니다.

**Comment by 5d-jh** [comment]
DB에 있는 데이터를 업데이트했습니다. 확인 부탁드려요

**Comment by sboh1214** [comment]
확인했습니다. 빠른 업데이트 감사드립니다!
