### ISSUE TITLE
급식이 안뜹니다

### ISSUE THREAD

**Issue by cocoa12327** [5d-jh/school-menu-api#35]
**버그에 대해 설명해 주세요.**
stu.gbe.go.kr에 접속을 하지 못하여 급식을 못불러오는 일이 발생하였습니다.

**요청 URL**
stu.gbe.go.kr

**원래 예상했던 결과**
급식이 정상적으로 떠야합니다

**추가 정보**
확인해본 결과 경상북도 교육청 주소는 stu.gbe.kr로 바뀐것으로 보입니다

**Comment by 5d-jh** [comment]
코드 수정했습니다. 잘 되는지 확인 부탁드립니다

**Comment by cocoa12327** [comment]
잘 됩니다, 감사합니다
