### ISSUE TITLE
서버 디비에 오류가 있는 것 같습니다.

### ISSUE THREAD

**Issue by jugol** [5d-jh/school-menu-api#4]
https://schoolmenukr.ml/api/high/N100000194?year=2018&month=9

됨.

https://schoolmenukr.ml/api/high/N100000194?year=2018&month=11

안됨.

ㅜㅜ 문제는 없는 것 같은데 안되네요..

**Comment by jugol** [comment]
혹시 month가 두자리여서 그런건가.....ㄷㄷㄷ

**Comment by 5d-jh** [comment]
아직 11월달 급식이 나오지 않았는데 그러한 예외를 처리하지 못하여 발생하는 문제인 것 같습니다.

**Comment by 5d-jh** [comment]
관련 코드를 수정했습니다. 혹시 이제 빈 페이지 대신 빈 배열이 뜨나요?

**Comment by godrb** [comment]
제가 이분꺼를 보고 했기에 저도 답변 남겨봅니다.
빈 페이지 대신 빈 배열 뜨구요.
다만, 급식 날짜가 하루씩 밀려서 나오는 것 같습니다.
10월 10일 급식들이 10월 11일에 표기가 되더군요.
확인 후 수정 부탁드립니다

**Comment by godrb** [comment]
네네 정상적으로 잘 불러와집니다
감사합니다 😄
