### ISSUE TITLE
[버그] date 변수가 0으로 시작하면 식단을 불러올 수 없음

### ISSUE THREAD

**Issue by ruwaku** [5d-jh/school-menu-api#41]
**버그에 대해 설명해 주세요.**
어떤 버그인지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴가 뜨지 않습니다.)
식단 API를 이용할 때 date 변수가 0으로 시작하면 식단을 불러올 수 없습니다.
(month 변수는 버그 없음)

**요청 URL**
어떤 URL로 요청해야 버그를 볼 수 있는지 알려주세요. (예: schoolmenukr.ml/api/high/ASDF?year=2020)

서울계성초등학교(B100002365) 예시:
https://schoolmenukr.ml/api/high/B100002365?year=2021&month=04&date=8 (정상)
https://schoolmenukr.ml/api/high/B100002365?year=2021&month=04&date=08 (오류)
https://schoolmenukr.ml/api/high/B100002365?year=2021&month=4&date=08 (오류)
https://schoolmenukr.ml/api/high/B100002365?year=2021&month=4&date=29 (정상)

**Comment by 5d-jh** [comment]
새 빌드로 업데이트했습니다. 잘 되는지 확인 부탁드려요
