### ISSUE TITLE
[버그] 급식을 불러올 수 없음

### ISSUE THREAD

**Issue by Sene1** [5d-jh/school-menu-api#42]
**버그에 대해 설명해 주세요.**
어떤 버그인지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴가 뜨지 않습니다.)

학교의 12일 부터 급식을 표시할 수 없음

**요청 URL**
어떤 URL로 요청해야 버그를 볼 수 있는지 알려주세요. (예: schoolmenukr.ml/api/high/ASDF?year=2020)

https://schoolmenukr.ml/api/high/N100000191?year=2021&month=4&date

**원래 예상했던 결과**
원래 어떤 결과가 나와야 하는지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴도 떠야 합니다.)

급식 정보가 있어야함.

**추가 정보**
버그와 관련된 추가 정보가 있다면 적어주세요.

**Comment by 5d-jh** [comment]
디비를 업데이트했습니다. 이제 잘되는지 확인 부탁드려요.

**Comment by Sene1** [comment]
잘 불러오네요
