### ISSUE TITLE
[버그] Url이 작동하지 않는 것 같습니다 😥

### ISSUE THREAD

**Issue by JJJJYO** [5d-jh/school-menu-api#44]
**버그에 대해 설명해 주세요.**
접속조차 안 됩니다

**요청 URL**
schoolmenukr.ml

**원래 예상했던 결과**
급식, 학교 코드 조회

**추가 정보**
URL!

**Comment by 5d-jh** [comment]
schoolmenukr.ml은 깃허브 홈페이지로 리다이렉션되도록 설계됐습니다. 사용 방법을 자세히 읽고 다시 시도 부탁드립니다!

**Comment by 5d-jh** [comment]
추가로 처음 학교 식단을 가져올 때는 NEIS 서버에서 직접 가져오는거라 많이 느릴 수 있다는 점 참고 부탁드립니다.

**Comment by JJJJYO** [comment]
schoolmenukr.ml 들어가니까 깃헙으로 와지지도 않고 원래 사용하다가 갑자기 정보를 못 불러옵니다 😓

**Comment by 5d-jh** [comment]
확인해보니 도메인 상에 문제가 발생한 것 같습니다. 일단 다음 주소로 접속하시면 정상적으로 사용할 수 있습니다.

`https://us-central1-school-api-a5575.cloudfunctions.net/api/api/[학교유형]/[학교코드]`

**Comment by JJJJYO** [comment]
감사합니다!
.ml도메인 보니까 freenom이신 것 같은데 쓰고있는데 저만 freenom도메인 먹통이 아니었군요 ㅜㅜ

**Comment by 5d-jh** [comment]
아하 알려주셔서 감사합니다! 추후 도메인을 바꾸던지 해야겠네요

**Comment by 5d-jh** [comment]
일단 지금은 정상 작동하는걸 보니 일시적인 오류였나보네요. 이 이슈는 닫도록 하겠습니다.

**Comment by JJJJYO** [comment]
schoolmenukr.ml URL 작동은 여전히 안 하는 것 같고 제공해주신 URL로 요청을 보내니 CORS 관련 오류로 응답하네요..

**Comment by 5d-jh** [comment]
> 일단 지금은 정상 작동하는걸 보니 일시적인 오류였나보네요.

이 부분은 아마 dns 캐싱때문에 제 환경에서는 정상적으로 확인됐었던 것 같습니다.

DNS 세팅을 재설정했고, 이제는 정상적으로 접속 되실겁니다(추가로 제가 확인해본 결과 schoolmenukr.ml로 접속하면 CORS 오류도 없을 것으로 예상합니다). 이슈 확인에 살짝 차질이 있던점 죄송합니다ㅠ

**Comment by JJJJYO** [comment]
DNS가 전파되기까지 좀 걸릴 것 같으니 오늘 밤쯤 다시 확인해보겠습니다. 도움 주셔서 감사합니다 😁

**Comment by 5d-jh** [comment]
혹시 지금은 잘 되는지 확인 부탁드립니다!

**Comment by JJJJYO** [comment]
답변이 너무 늦었네요 ㅜㅜ 
**지금 너무 잘 작동합니다~!**
