### ISSUE TITLE
급식이 표출되지않습니다

### ISSUE THREAD

**Issue by ka6865** [5d-jh/school-menu-api#5]
https://schoolmenukr.ml/api/high/J100000603?year=2018&month=10
이곳 학교주소의 급식이 뜨질않네요

**Comment by 5d-jh** [comment]
조식, 중식, 석식 중 하나만 있는 경우를 생각하지 못했네요..ㅠ

 관련 코드를 수정했습니다. 잘 불러와지는지 확인 바랍니다
