### ISSUE TITLE
급식을 불러오지 못합니다

### ISSUE THREAD

**Issue by godrb** [5d-jh/school-menu-api#6]
https://schoolmenukr.ml/api/high/N100000194?month=10
이 학교코드를 사용하여 오랜만에 급식 플친을 활성화 시켜봤는데
급식을 제대로 불러오지 못합니다.
https://schoolmenukr.ml/api/high/N100000194?month=11
이렇게도 해봤는데 11월 1일 조식 이거 하나만 있더군요..
10월달 남은 일은 아예 불러오지 못하고, 11월은 아직 메뉴가 없습니다.
확인 후 수정 부탁드립니다

**Comment by 5d-jh** [comment]
제대로 나오도록 조치했습니다. 아직 영양사님이 식단을 다 작성하지 못하셨는지 11월달은 5일까지밖에 나오지 않는 것 같습니다.
앞으로 이런 일이 발생하지 않도록 코드를 수정하고 있습니다.
