### ISSUE TITLE
[버그] schoolmenukr.ml 도메인이 작동하지 않습니다.

### ISSUE THREAD

**Issue by hlog2e** [5d-jh/school-menu-api#63]
**버그에 대해 설명해 주세요.**
어떤 버그인지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴가 뜨지 않습니다.)

-- schoolmenukr.ml 자체 URL로 데이터를 불러 올 수 없습니다.

**요청 URL**
어떤 URL로 요청해야 버그를 볼 수 있는지 알려주세요. (예: schoolmenukr.ml/api/high/ASDF?year=2020)

-- schoolmenukr.ml

**추가 정보**
버그와 관련된 추가 정보가 있다면 적어주세요.

-- https://us-central1-school-api-a5575.cloudfunctions.net/api/api/
이전 이슈에서 나와있는 이 주소로 접속하여 조회하면 정상 작동됩니다. 도메인에 문제가 있는거 같습니다. 처리 부탁드립니다.

**Comment by hlog2e** [comment]
방금 다시 확인해보니, KT ISP 에서만 문제가 발생하네요.. LG U플러스 인터넷 사용시 정상 접속 됩니다.

**Comment by 5d-jh** [comment]
이 부분은 도메인 제공사의 문제인 것 같아서 조금 더 지켜보겠습니다
