### ISSUE TITLE
[버그] 충남도교육청 급식을 불러올 수 없음

### ISSUE THREAD

**Issue by Sene1** [5d-jh/school-menu-api#77]
**버그에 대해 설명해 주세요.**
어떤 버그인지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴가 뜨지 않습니다.)

{"server_message":["문제가 발생했거나 건의사항이 있는 경우 GitHub 저장소 페이지에 이슈를 남겨주세요: https://github.com/5d-jh/school-menu-api/issues","오류: request to https://stu.cne.kr/sts_sci_md00_001.do?schulCode=N100000191&schulCrseScCode=4&ay=2021&mm=12 failed, reason: getaddrinfo EAI_AGAIN stu.cne.kr"],"menu":[]}

**요청 URL**
어떤 URL로 요청해야 버그를 볼 수 있는지 알려주세요. (예: schoolmenukr.ml/api/high/ASDF?year=2020)

https://schoolmenukr.ml/api/high/N100000191?date=08

**원래 예상했던 결과**
원래 어떤 결과가 나와야 하는지 간단하고 명료하게 설명해 주세요. (예: 특수기호가 있는 메뉴도 떠야 합니다.)

김밥볶음밥
1.2.5.6.10.13.
종합어묵무국
1.5.6.
떡볶이+김말이
1.5.6.10.13.
배추김치
9.
파인한자몽
13.
다크초코아몬드
2.5.

**추가 정보**
버그와 관련된 추가 정보가 있다면 적어주세요.

충청남도교육청 URL이 stu.cne.go.kr 인데 오류 보면 stu.cne.kr 이네요.

**Comment by 5d-jh** [comment]
제가 개인적으로 바빠서 빨리 해결되지 않을 수도 있습니다. 만약 이슈 해결 진행이 너무 늦어지는 것 같아서 직접 수정하고 싶으시면 말씀해주세요.

**Comment by Sene1** [comment]
> 제가 개인적으로 바빠서 빨리 해결되지 않을 수도 있습니다. 만약 이슈 해결 진행이 너무 늦어지는 것 같아서 직접 수정하고 싶으시면 말씀해주세요.

한번 직접 수정해보고 싶은데 풀리퀘 하면 되나요?

**Comment by 5d-jh** [comment]
그냥 풀리퀘 해주시면 제가 리뷰해 보고 배포할게요.

package-school-menu에서 코드 수정하시고 [여기](https://github.com/5d-jh/school-menu-api/blob/master/functions/package-school-menu/test/test.ts)서 테스트 코드까지 작성해 주신다면 감사하겠습니다. 모르는 부분 있으시면 바로 불어봐주세요
