### ISSUE TITLE
급식을 불러오지 못합니다

### ISSUE THREAD

**Issue by Andy-0414** [5d-jh/school-menu-api#8]
https://schoolmenukr.ml/api/high/B100000658?month=12&year=2018
11월 급식까진 불러와지지만 12월달 급식을 불러오지 못합니다

**Comment by 5d-jh** [comment]
식단 임시저장이 제대로 되지 않아 발생한 문제같으며 해결했습니다. 잘 불러와지나요?

**Comment by Andy-0414** [comment]
잘 불러와집니다 감사합니다!
