### ISSUE TITLE
18일부터 급식이 없다고 뜹니다.

### ISSUE THREAD

**Issue by godrb** [5d-jh/school-menu-api#9]
https://schoolmenukr.ml/api/high/N100000194?month=12

17일도 아침꺼밖에 출력이 되지 않으며,
18일부터는 아예 출력이 되지 않습니다.
확인 부탁드립니다.

**Comment by 5d-jh** [comment]
제대로 출력되도록 조치했습니다. 잘 불러와지는지 확인 바랍니다

**Comment by godrb** [comment]
죄송합니다 기억이 나질 않네요...ㅎ
금방 테스트 해보니까 잘 되네요.
감사합니다 😆

**Comment by 5d-jh** [comment]
아닙니다 제가 꼼꼼히 확인하지 않은 탓입니다ㅋㅋ 항상 피드백 주셔서 감사할 따름입니다.
