### ISSUE TITLE
[버그] DNS 오류로 인한 접속 불가

### ISSUE THREAD

**Issue by Hello50511** [5d-jh/school-menu-api#96]
**버그에 대해 설명해 주세요.**
사이트가 막혔습니다

**요청 URL**
https://schoolmenukr.ml/code/api?q=

**원래 예상했던 결과**
json 형식의 api가 나와야합니다

**추가 정보**
없음

**Comment by 5d-jh** [comment]
서버 비용 과다 청구로 인해 일정 트래픽을 초과하면 한시간 동안 특정 ip를 차단하도록 설정했습니다. 한시간 후 다시 확인 바랍니다.

**Comment by 5d-jh** [comment]
혹시 막혔을 때 응답 헤더가 어떻게 오는지 보여주실 수 있으신가요?

**Comment by Hello50511** [comment]
네 DNS_PROBE_FINISHED_NXDOMAIN 입니다

**Comment by 5d-jh** [comment]
DNS 오류네요 schoolmenukr.ml 은 정상화될 때까지 기다려야 할 것 같고 school-api-a5575.firebaseapp.com 으로 접속하시면 잘 될 수 있습니다.

**Comment by Hello50511** [comment]
넵

**Comment by 5d-jh** [comment]
이상 없으면 이슈 닫도록 할게요

**Comment by Hello50511** [comment]
넵
